<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Role_ID</name>
   <tag></tag>
   <elementGuidId>15e8f5e8-db88-473d-b39f-915ac9786171</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;rdtInfoPane&quot;]/workflow-panel/div[3]/div/div[1]/div[2]/div/eea-template/form/div/div[2]/lookup/select[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
