<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Addres_Asset</name>
   <tag></tag>
   <elementGuidId>517ef779-31c2-4187-ab26-3e4e3c97ccc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='adtInfoPane']/workflow-panel/div[3]/div/div/div[2]/div/adt-template/form/div/div[3]/lookup[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>disabled</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>ngClass</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-hide</name>
      <type>Main</type>
      <value>busy</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-valid ng-touched</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>('' + d.id) as d.name for d in data</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>bindModel</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>lookup_change(bindModel)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(Please Select)10560 W Savannah Place, Vero Beach, Florida (Liability)10560 W Savannah Place, Vero Beach, Florida 329631102 Harbor Drive, Delray Beach, FL 33483116 Edwards Drive, Morehead City, NC117 Buck Heights Lane &amp; Boat House124 Magnolia Street, Spartanburg, SC 293021339 Oak Street, Eugene, Oregon1505 Park Lake Street, Orlando, FL 32803151 Spooners St S, Morehead City, NC165 Mondamin Road Lake Summit, Tuxedo172 E Main Olive Garden Property172 East Main Street, Spartanburg, SC 293022016 Petworth, Raleigh, NC 2761521 Chelsea, New York, NY 1001124 Ashwood Road, Port Washington, NY 100502427 Wallace Avenue, Spartanburg, SC2492 Old Knox Road2513 Evans Street, Morehead City, NC275 Northstar Investor LLC.29 Westerly Road, Westerly, RI  028912932 Luvan Blvd, Georgetown, SC (net)30 Lake Forest Drive, Spartanburg, SC308 Everett St. Laurinburg, NC 29622314 S. Pine St. - Office Bldg.314 South LLC314 South LLC 100% Membership315 E New England Ave Winter Park FL Condo3290 N Pleasantburg Dr, Greenville, SC3301 Evans St, Morehead City, NC4222 Fox Brook Lane, Charlotte, NC 282114930 Upper Cattle Creek Rd Carbondale, Co 816234930 Upper Cattle Creek Road, Carbondale, Colorado (Liability)4930 Upper Cattle Creek Road, Carbondale, Colorado 8162356 Shorebird Loop, Pawley's Island, SC61 Hillside Drive, LLC72 Buck Heights Lane Lake Summit836 Whiskey Road, Aiken, SC 29801940 E. Deerpath Rd, Lake Forest, IL 60045Alexandria Real Estate Equities, IncAmerican Capital Agency Corp.Arrowhead Farms, LLCBaron Real Estate InstitutionalBauknight &amp; Babb, LLCBick - Real Estate Lot #450Bre Properties Class ABreakwater Plantation, LLCBrookwood U.S. Real Estate Onshore Fund LP-Budgeted Future CallBrookwood U.S. Real Estate Onshore Fund LP-CommitmentBrookwood US Real Estate Onshore Fund LPC/O Agence Eugster Sa Verbier 1946 SwitzerlandCapital Call Reserve - ReCapstead Mortgage CorpCare Capital Properties IncCase-Shiller Home Price IndexCharleston CondominiumChimera Investment CorpClarence W. Gosnell, IncCohen &amp; Steers Global Realty ACohen &amp; Steers Instl Realty SharesCohen &amp; Steers Realty SharesCommit To Pur - Trinity Capital Value Fd III, LPCommit To Pur-Kayne Anderson Real Estate Ptnrs II, LPCommit To Pur-Nch New Europe Property Fd II, LPCommit To Purchase Karep IIICover Creek LLC: CondoCrescent Summit Holding LLC 100% MembershipCrescent Summit Holdings, LLCDebordieu - 1/2 Lot #16Debordieu - 1/2 Lot #2Delapp Montana, LLCDfs Capital Partners Commit To PurchaseDiamondrock Hospitality CoDigital Realty Trust IncDSF Cap Partners III LPDSF Cap Partners III LP-Budgeted Future CallDSF Cap Partners III LP-CommitmentDSF Capital Partners IV LPDSF Capital Partners IV LP-Budgeted Future CallDSF Capital Partners IV LP-CommitmentDSF Multi-Family Real Estate Fund III LPEchota Condo, Boone, NCEquinix IncEssex Property Trust IncExclusive ResortsExtra Space Storage IncFirst Industrial Realty Trust IncFirst Potomac Realty TrustFour Corners Property Trust IncGallants Landing Site #6Gosnell Properties, IncGrand Dunes Lot, Myrtle Beach, SC 29572Harrison County Real Estate 25% mineral interestHCP IncHealth Care REIT IncHome Properties IncHZB LLC Membership CertificateIA Gloucester Terrace, Myrtle Beach, SC 29572Invesco Mortgage Capital InciShares US Real Estate ETFJackson County, WV LandJones Lang Lasalle Income Property Trust, IncJones Lang Lasalle Income Property Trust-Budgeted Future CallJones Lang Lasalle Income Property Trust-CommitmentKanawha County WV LandKayne Anderson Re Partners III-Budgeted Future CallKayne Anderson Re Partners III-CommitmentKayne Anderson Real Estate Partners II LPKayne Anderson Real Estate Partners II LPKayne Anderson Real Estate Partners III LPKayne Anderson Real Estate Partners IV LPKayne Anderson Real Estate Partners IV LP-Budgeted Future CallKayne Anderson Real Estate Partners IV LP-CommitmentKayne Anderson Real Estate Partners LP -Budgeted Future CallKayne Anderson Real Estate Partners LP -CommitmentKimco Realty CorpLakeview CallLakeview PartnersLakeview PartnersLakeview Partners  -Budgeted Future CallLakeview Partners  -CommitmentLaSalle Hotel PropertiesLexington Realty TrustLipper Real Estate FundsLot SR1952 S Lake Summit Parcell 9962923McDonald Ventures XXXV LLCMedical Properties Trust IncMontana SC II LLC 100% Membership  Montana Sc II, LLCMorningstar Us REIT Index TrMsb REIT V  Inc-Budgeted Future CallMsb REIT V  Inc-CommitmentMSB REIT V, IncMullet Lake House LPNAI Investment Management, LLCNAREIT Equity IndexNch New Europe Property Fund II  LP-Budgeted Future CallNch New Europe Property Fund II  LP-CommitmentNCH New Europe Property Fund II, LPNCH XI LPNCH XI LP - 2662Nch Xi LP - 2663 / 2664-Budgeted Future CallNch Xi LP - 2663 / 2664-CommitmentOaklane Fund I LLC Cl AOaklane Fund I LLC Cl BOaklane Fund I LLC Cl B  -Budgeted Future CallOaklane Fund I LLC Cl B  -CommitmentPalmetto Belk, LLCPebblebrook Hotel TrustPine Street Lot - .50 acrePine Street Lot - .58 acrePine Street Lot - .84 acrePrince Creek South LLCPrince Creek South LLC  -Budgeted Future CallPrince Creek South LLC  -CommitmentPrince Creek South LLC (1)Public StorageReal Estate (Specialized) - Proforma-Cap CallReal Estate (Specialized) - Proforma-Non-InvestmentReal Estate (Specialized) - Proforma-RebalanceReal Estate (Specialized) - Proforma-ScenarioReal Estate - Family Investments - Proforma-Cap CallReal Estate - Family Investments - Proforma-Non-InvestmentReal Estate - Family Investments - Proforma-RebalanceReal Estate - Family Investments - Proforma-ScenarioReal Estate - Funds   - Proforma-Cap CallReal Estate - Funds   - Proforma-Non-InvestmentReal Estate - Funds   - Proforma-RebalanceReal Estate - Funds   - Proforma-ScenarioReal Estate - Funds - Proforma-Cap CallReal Estate - Funds - Proforma-Non-InvestmentReal Estate - Funds - Proforma-RebalanceReal Estate - Funds - Proforma-ScenarioReal Estate - Investment Deals - Proforma-Cap CallReal Estate - Investment Deals - Proforma-Non-InvestmentReal Estate - Investment Deals - Proforma-RebalanceReal Estate - Investment Deals - Proforma-ScenarioReal Estate - Land - Proforma-Cap CallReal Estate - Land - Proforma-Non-InvestmentReal Estate - Land - Proforma-RebalanceReal Estate - Land - Proforma-ScenarioReal Estate - Personal - Proforma-Cap CallReal Estate - Personal - Proforma-Non-InvestmentReal Estate - Personal - Proforma-RebalanceReal Estate - Personal - Proforma-ScenarioReal Estate Funds (Concentrated) - Proforma-Cap CallReal Estate Funds (Concentrated) - Proforma-Non-InvestmentReal Estate Funds (Concentrated) - Proforma-RebalanceReal Estate Funds (Concentrated) - Proforma-ScenarioRealty Income CorpREITs - Proforma-Cap CallREITs - Proforma-Non-InvestmentREITs - Proforma-RebalanceREITs - Proforma-ScenarioRems Real Estate Income 50/50 FundREMS Real Estate Income 50/50 InstlREMS Real Estate Value Opportunity InstlRosebank Plantation, LLC (house)Sandpiper Ct., Myrtle Beach, SC 29572SB PartnersSecond BH - Parcel #9965512 - 108 S Summit Ridge RoadSenior Housing Properties TrustSimon Property Group IncSL Green Realty CorpSpa Creek Club LLCSPDR Dow Jones International RelEst ETFStarwood Property Trust IncT. Rowe Price Real EstateThe Billows Apt. No. 30, Naples, FL 34103The Old Magnolia Bordello LLCThe Rems Real Estate Value- Opportunities FundThird Avenue Real Estate Value FundThird Avenue Real Estate Value InvestorThomas Point Light: WarehouseTrinity CapitalTrinity Capital Value Fund III LPTrinity Capital Value Fund III LP  -Budgeted Future CallTrinity Capital Value Fund III LP  -CommitmentTucker Woods LLC Variable InterestUDR IncUnit 803 Highlands Mountain Club CondominiumsVandalia Real Estate LLCVandalia Real Estate LLCVanguard Real Estate ETFVanguard Real Estate Index AdmiralVanguard Real Estate Index InstitutionalVanguard Real Estate Index InvestorVIllages At Pecan Grove LLCVornado Realty TrustWashington Prime GroupWashington REITWaterford Development LLCWB, LLC - 420 Gulf Blvd, Boca Grande, FL (net)WBP LLCWeingarten Realty InvestorsWells Real Estate InvestmentWells Real Estate Investment  -Budgeted Future CallWells Real Estate Investment  -CommitmentWelltower IncWhiteside FundWye River LLC</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adtInfoPane&quot;)/workflow-panel[1]/div[3]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane active&quot;]/div[2]/div[1]/adt-template[1]/form[@class=&quot;form-horizontal workflow-panel ng-pristine ng-valid&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-4&quot;]/lookup[@class=&quot;ng-pristine ng-untouched ng-valid&quot;]/select[@class=&quot;form-control ng-pristine ng-valid ng-touched&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='adtInfoPane']/workflow-panel/div[3]/div/div/div[2]/div/adt-template/form/div/div[3]/lookup[2]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Status'])[1]/following::select[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Description'])[1]/preceding::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Notes'])[1]/preceding::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//lookup[2]/select</value>
   </webElementXpaths>
</WebElementEntity>
