<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>close_Button</name>
   <tag></tag>
   <elementGuidId>4648bafb-f49a-4a2b-9432-1bbeba59b957</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;crmRelationshipViewer&quot;]/crm-relationship-viewer/div[1]/div[1]/button
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
